int main()
{
    
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int     int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;inc=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int ct a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    in;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,it c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
  nt b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=  int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
   a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    i    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,intnt a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
     b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    ib;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+bnt c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,i;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;nt b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int ;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;i c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
}