int main()
{
    
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
     int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;int a,int b;
    int c=a+b;
    return 0;
}